*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Mar  2 17:13:06 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 03 January 2019 15:51:46
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iZuf65d0f9utpg736bx6i1Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/admin/mysite-random
writing pidfile to /home/admin/mysite-random/uwsgi/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/admin/mysite-random
your processes number limit is 7277
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Jan  3 2019, 23:47:25)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xf41820
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xf41820 pid: 18475 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18475)
spawned uWSGI worker 1 (pid: 18479, cores: 1)
spawned uWSGI worker 2 (pid: 18480, cores: 1)
*** Stats server enabled on /home/admin/mysite-random/uwsgi/uwsgi.status fd: 12 ***
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /cache/global/img/gs.gif
[pid: 18480|app: 0|req: 1/1] 80.82.70.187 () {32 vars in 418 bytes} [Sat Mar  2 17:13:07 2019] GET /cache/global/img/gs.gif => generated 54643 bytes in 116 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(7)
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(6)
Internal Server Error: /polls/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[pid: 18480|app: 0|req: 2/2] 183.157.160.29 () {42 vars in 817 bytes} [Sat Mar  2 17:13:32 2019] GET /polls/ => generated 170551 bytes in 4106 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[pid: 18479|app: 0|req: 1/3] 183.157.160.29 () {42 vars in 804 bytes} [Sat Mar  2 17:13:28 2019] GET / => generated 170472 bytes in 8648 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[pid: 18480|app: 0|req: 3/4] 183.157.160.29 () {42 vars in 791 bytes} [Sat Mar  2 17:13:38 2019] GET /favicon.ico => generated 185995 bytes in 94 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /polls/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/python3/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
[pid: 18479|app: 0|req: 2/5] 183.157.160.29 () {44 vars in 848 bytes} [Sat Mar  2 17:13:57 2019] GET /polls/ => generated 251594 bytes in 884 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/python3/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
[pid: 18480|app: 0|req: 4/6] 183.157.160.29 () {46 vars in 844 bytes} [Sat Mar  2 17:13:59 2019] GET /favicon.ico => generated 267164 bytes in 638 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /polls/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/python3/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
[pid: 18479|app: 0|req: 3/7] 183.157.160.29 () {44 vars in 848 bytes} [Sat Mar  2 17:14:25 2019] GET /polls/ => generated 251594 bytes in 167 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/python3/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
[pid: 18480|app: 0|req: 5/8] 183.157.160.29 () {46 vars in 844 bytes} [Sat Mar  2 17:14:26 2019] GET /favicon.ico => generated 267164 bytes in 134 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Mar  2 17:27:10 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 03 January 2019 15:51:46
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iZuf65d0f9utpg736bx6i1Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/admin/mysite-random
writing pidfile to /home/admin/mysite-random/uwsgi/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/admin/mysite-random
your processes number limit is 7277
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Jan  3 2019, 23:47:25)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xada820
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xada820 pid: 18793 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18793)
spawned uWSGI worker 1 (pid: 18796, cores: 1)
spawned uWSGI worker 2 (pid: 18797, cores: 1)
*** Stats server enabled on /home/admin/mysite-random/uwsgi/uwsgi.status fd: 12 ***
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(6)
Internal Server Error: /polls/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/python3/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
[pid: 18797|app: 0|req: 1/1] 183.157.160.29 () {42 vars in 817 bytes} [Sat Mar  2 17:27:19 2019] GET /polls/ => generated 251459 bytes in 3109 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(7)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 3, in <module>
    from .env import ranking_agent
  File "./polls/env.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/python3/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/python3/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
[pid: 18796|app: 0|req: 1/2] 183.157.160.29 () {42 vars in 791 bytes} [Sat Mar  2 17:27:23 2019] GET /favicon.ico => generated 266903 bytes in 3106 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Mar  2 17:48:05 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 03 January 2019 15:51:46
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iZuf65d0f9utpg736bx6i1Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/admin/mysite-random
writing pidfile to /home/admin/mysite-random/uwsgi/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/admin/mysite-random
your processes number limit is 7277
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Jan  3 2019, 23:47:25)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ad8820
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1ad8820 pid: 19072 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19072)
spawned uWSGI worker 1 (pid: 19076, cores: 1)
spawned uWSGI worker 2 (pid: 19077, cores: 1)
*** Stats server enabled on /home/admin/mysite-random/uwsgi/uwsgi.status fd: 12 ***
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(7)
Internal Server Error: /polls/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 5, in <module>
    from .utils import BmapConfig, BmapPlotter
  File "./polls/utils.py", line 7, in <module>
    matplotlib.rcParams['toolbar'] = 'None'
NameError: name 'matplotlib' is not defined
[pid: 19076|app: 0|req: 1/1] 183.157.160.29 () {44 vars in 848 bytes} [Sat Mar  2 17:48:08 2019] GET /polls/ => generated 171319 bytes in 2522 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(6)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 5, in <module>
    from .utils import BmapConfig, BmapPlotter
  File "./polls/utils.py", line 7, in <module>
    matplotlib.rcParams['toolbar'] = 'None'
NameError: name 'matplotlib' is not defined
[pid: 19077|app: 0|req: 1/2] 183.157.160.29 () {46 vars in 844 bytes} [Sat Mar  2 17:48:12 2019] GET /favicon.ico => generated 186889 bytes in 2525 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /polls/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 5, in <module>
    from .utils import BmapConfig, BmapPlotter
ImportError: cannot import name 'BmapPlotter'
[pid: 19076|app: 0|req: 2/3] 183.157.160.29 () {44 vars in 848 bytes} [Sat Mar  2 17:48:36 2019] GET /polls/ => generated 159870 bytes in 82 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/local/python3/lib/python3.6/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/python3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mysite/urls.py", line 20, in <module>
    path('polls/', include('polls.urls')),
  File "/usr/local/python3/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./polls/urls.py", line 3, in <module>
    from . import views
  File "./polls/views.py", line 12, in <module>
    from .test_server import get_pair,  calc_params
  File "./polls/test_server.py", line 5, in <module>
    from .utils import BmapConfig, BmapPlotter
ImportError: cannot import name 'BmapPlotter'
[pid: 19077|app: 0|req: 2/4] 183.157.160.29 () {46 vars in 844 bytes} [Sat Mar  2 17:48:37 2019] GET /favicon.ico => generated 175440 bytes in 87 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
[pid: 19076|app: 0|req: 3/5] 183.157.160.29 () {44 vars in 848 bytes} [Sat Mar  2 17:49:20 2019] GET /polls/ => generated 8222 bytes in 51 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
Not Found: /static/jumbotron.css
[pid: 19076|app: 0|req: 4/6] 183.157.160.29 () {42 vars in 787 bytes} [Sat Mar  2 17:49:20 2019] GET /static/jumbotron.css => generated 2106 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/css/bootstrap.min.css
[pid: 19077|app: 0|req: 3/7] 183.157.160.29 () {42 vars in 814 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/css/bootstrap.min.css => generated 2145 bytes in 12 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/css/particles.css
[pid: 19077|app: 0|req: 4/8] 183.157.160.29 () {42 vars in 805 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/css/particles.css => generated 2133 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/jquery.min.js
[pid: 19077|app: 0|req: 5/9] 183.157.160.29 () {42 vars in 789 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/jquery.min.js => generated 2130 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19076|app: 0|req: 5/10] 183.157.160.29 () {42 vars in 794 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/particles.min.js => generated 2139 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19077|app: 0|req: 6/11] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/bootstrap.min.js => generated 2139 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19077|app: 0|req: 7/12] 183.157.160.29 () {42 vars in 787 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/particles.js => generated 2127 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/jquery.min.js
[pid: 19077|app: 0|req: 8/13] 183.157.160.29 () {42 vars in 788 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/jquery.min.js => generated 2130 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19076|app: 0|req: 6/14] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/bootstrap.min.js => generated 2139 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19076|app: 0|req: 7/15] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/particles.min.js => generated 2139 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19077|app: 0|req: 9/16] 183.157.160.29 () {42 vars in 787 bytes} [Sat Mar  2 17:49:20 2019] GET /static/dist/js/particles.js => generated 2127 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 19076|app: 0|req: 8/17] 183.157.160.29 () {46 vars in 844 bytes} [Sat Mar  2 17:49:20 2019] GET /favicon.ico => generated 2079 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Mar  2 18:02:59 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 03 January 2019 15:51:46
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iZuf65d0f9utpg736bx6i1Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/admin/mysite-random
writing pidfile to /home/admin/mysite-random/uwsgi/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/admin/mysite-random
your processes number limit is 7277
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Jan  3 2019, 23:47:25)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xcfa820
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xcfa820 pid: 19238 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19238)
spawned uWSGI worker 1 (pid: 19240, cores: 1)
spawned uWSGI worker 2 (pid: 19241, cores: 1)
*** Stats server enabled on /home/admin/mysite-random/uwsgi/uwsgi.status fd: 12 ***
*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Mar  2 18:03:45 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 03 January 2019 15:51:46
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iZuf65d0f9utpg736bx6i1Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/admin/mysite-random
writing pidfile to /home/admin/mysite-random/uwsgi/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/admin/mysite-random
your processes number limit is 7277
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Jan  3 2019, 23:47:25)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x199d820
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x199d820 pid: 19254 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19254)
spawned uWSGI worker 1 (pid: 19256, cores: 1)
spawned uWSGI worker 2 (pid: 19257, cores: 1)
*** Stats server enabled on /home/admin/mysite-random/uwsgi/uwsgi.status fd: 12 ***
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(7)
[pid: 19256|app: 0|req: 1/1] 183.157.160.29 () {44 vars in 848 bytes} [Sat Mar  2 18:03:51 2019] GET /polls/ => generated 8222 bytes in 2557 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
Not Found: /static/jumbotron.css
[pid: 19256|app: 0|req: 2/2] 183.157.160.29 () {42 vars in 788 bytes} [Sat Mar  2 18:03:54 2019] GET /static/jumbotron.css => generated 2106 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/css/particles.css
[pid: 19256|app: 0|req: 3/3] 183.157.160.29 () {42 vars in 806 bytes} [Sat Mar  2 18:03:54 2019] GET /static/dist/css/particles.css => generated 2133 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19256|app: 0|req: 4/4] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 18:03:54 2019] GET /static/dist/js/bootstrap.min.js => generated 2139 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/jquery.min.js
[pid: 19256|app: 0|req: 5/5] 183.157.160.29 () {42 vars in 789 bytes} [Sat Mar  2 18:03:54 2019] GET /static/dist/js/jquery.min.js => generated 2130 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19256|app: 0|req: 6/6] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 18:03:54 2019] GET /static/dist/js/particles.min.js => generated 2139 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19256|app: 0|req: 7/7] 183.157.160.29 () {42 vars in 787 bytes} [Sat Mar  2 18:03:54 2019] GET /static/dist/js/particles.js => generated 2127 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(6)
Not Found: /static/dist/css/bootstrap.min.css
[pid: 19257|app: 0|req: 1/8] 183.157.160.29 () {42 vars in 814 bytes} [Sat Mar  2 18:03:54 2019] GET /static/dist/css/bootstrap.min.css => generated 2145 bytes in 2534 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19256|app: 0|req: 8/9] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 18:03:56 2019] GET /static/dist/js/bootstrap.min.js => generated 2139 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19256|app: 0|req: 9/10] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 18:03:56 2019] GET /static/dist/js/particles.min.js => generated 2139 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19257|app: 0|req: 2/11] 183.157.160.29 () {42 vars in 787 bytes} [Sat Mar  2 18:03:56 2019] GET /static/dist/js/particles.js => generated 2127 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Mar  2 18:11:22 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 03 January 2019 15:51:46
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iZuf65d0f9utpg736bx6i1Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/admin/mysite-random
writing pidfile to /home/admin/mysite-random/uwsgi/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/admin/mysite-random
your processes number limit is 7277
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Jan  3 2019, 23:47:25)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x137f820
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x137f820 pid: 19319 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19319)
spawned uWSGI worker 1 (pid: 19321, cores: 1)
spawned uWSGI worker 2 (pid: 19322, cores: 1)
*** Stats server enabled on /home/admin/mysite-random/uwsgi/uwsgi.status fd: 12 ***
*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Mar  2 18:11:29 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 03 January 2019 15:51:46
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: iZuf65d0f9utpg736bx6i1Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/admin/mysite-random
writing pidfile to /home/admin/mysite-random/uwsgi/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/admin/mysite-random
your processes number limit is 7277
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.3 (default, Jan  3 2019, 23:47:25)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x21f0820
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x21f0820 pid: 19333 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19333)
spawned uWSGI worker 1 (pid: 19336, cores: 1)
spawned uWSGI worker 2 (pid: 19337, cores: 1)
*** Stats server enabled on /home/admin/mysite-random/uwsgi/uwsgi.status fd: 12 ***
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(7)
[pid: 19336|app: 0|req: 1/1] 183.157.160.29 () {44 vars in 855 bytes} [Sat Mar  2 18:11:33 2019] GET /polls/ => generated 8222 bytes in 2485 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
Not Found: /static/jumbotron.css
[pid: 19336|app: 0|req: 2/2] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 18:11:36 2019] GET /static/jumbotron.css => generated 1796 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/css/particles.css
[pid: 19336|app: 0|req: 3/3] 183.157.160.29 () {42 vars in 813 bytes} [Sat Mar  2 18:11:36 2019] GET /static/dist/css/particles.css => generated 1823 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/jquery.min.js
[pid: 19336|app: 0|req: 4/4] 183.157.160.29 () {42 vars in 796 bytes} [Sat Mar  2 18:11:36 2019] GET /static/dist/js/jquery.min.js => generated 1820 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19336|app: 0|req: 5/5] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:11:36 2019] GET /static/dist/js/bootstrap.min.js => generated 1829 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19336|app: 0|req: 6/6] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:11:36 2019] GET /static/dist/js/particles.min.js => generated 1829 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19336|app: 0|req: 7/7] 183.157.160.29 () {42 vars in 794 bytes} [Sat Mar  2 18:11:36 2019] GET /static/dist/js/particles.js => generated 1817 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/jquery.min.js
[pid: 19336|app: 0|req: 8/8] 183.157.160.29 () {42 vars in 796 bytes} [Sat Mar  2 18:11:36 2019] GET /static/dist/js/jquery.min.js => generated 1820 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
unable to load configuration from from multiprocessing.semaphore_tracker import main;main(6)
Not Found: /static/dist/css/bootstrap.min.css
[pid: 19337|app: 0|req: 1/9] 183.157.160.29 () {42 vars in 821 bytes} [Sat Mar  2 18:11:36 2019] GET /static/dist/css/bootstrap.min.css => generated 1835 bytes in 2406 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19336|app: 0|req: 9/10] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:11:38 2019] GET /static/dist/js/bootstrap.min.js => generated 1829 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19336|app: 0|req: 10/11] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:11:38 2019] GET /static/dist/js/particles.min.js => generated 1829 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19337|app: 0|req: 2/12] 183.157.160.29 () {42 vars in 794 bytes} [Sat Mar  2 18:11:38 2019] GET /static/dist/js/particles.js => generated 1817 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/css/bootstrap.min.css
[pid: 19336|app: 0|req: 11/13] 183.157.160.29 () {42 vars in 878 bytes} [Sat Mar  2 18:13:43 2019] GET /static/dist/css/bootstrap.min.css => generated 1835 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 19336|app: 0|req: 12/14] 183.157.160.29 () {44 vars in 855 bytes} [Sat Mar  2 18:14:37 2019] GET /polls/ => generated 8222 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
Not Found: /static/dist/css/bootstrap.min.css
[pid: 19337|app: 0|req: 3/15] 183.157.160.29 () {42 vars in 821 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/css/bootstrap.min.css => generated 1835 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/jumbotron.css
[pid: 19337|app: 0|req: 4/16] 183.157.160.29 () {42 vars in 795 bytes} [Sat Mar  2 18:14:37 2019] GET /static/jumbotron.css => generated 1796 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/jquery.min.js
[pid: 19337|app: 0|req: 5/17] 183.157.160.29 () {42 vars in 796 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/jquery.min.js => generated 1820 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/css/particles.css
[pid: 19337|app: 0|req: 6/18] 183.157.160.29 () {42 vars in 813 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/css/particles.css => generated 1823 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19336|app: 0|req: 13/19] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/particles.min.js => generated 1829 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19336|app: 0|req: 14/20] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/bootstrap.min.js => generated 1829 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19337|app: 0|req: 7/21] 183.157.160.29 () {42 vars in 794 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/particles.js => generated 1817 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/jquery.min.js
[pid: 19337|app: 0|req: 8/22] 183.157.160.29 () {42 vars in 796 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/jquery.min.js => generated 1820 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/bootstrap.min.js
[pid: 19336|app: 0|req: 15/23] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/bootstrap.min.js => generated 1829 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.min.js
[pid: 19337|app: 0|req: 9/24] 183.157.160.29 () {42 vars in 802 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/particles.min.js => generated 1829 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/js/particles.js
[pid: 19336|app: 0|req: 16/25] 183.157.160.29 () {42 vars in 794 bytes} [Sat Mar  2 18:14:37 2019] GET /static/dist/js/particles.js => generated 1817 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /static/dist/css/particles.css
[pid: 19336|app: 0|req: 17/26] 183.157.160.29 () {42 vars in 870 bytes} [Sat Mar  2 18:15:43 2019] GET /static/dist/css/particles.css => generated 1823 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 19336|app: 0|req: 18/27] 2.187.90.114 () {32 vars in 457 bytes} [Sat Mar  2 18:34:26 2019] GET / => generated 2159 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 19336|app: 0|req: 19/28] 138.36.189.40 () {32 vars in 457 bytes} [Sat Mar  2 18:40:11 2019] GET / => generated 2159 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 19336|app: 0|req: 20/29] 164.138.236.154 () {36 vars in 516 bytes} [Sat Mar  2 18:45:53 2019] GET / => generated 2156 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
